#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.5
#  in conjunction with Tcl version 8.6
#    Aug 17, 2022 12:58:39 PM EDT  platform: Windows NT
#    Aug 17, 2022 12:59:16 PM EDT  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import filefixer

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    # _w1 = filefixer.OpenButton(_top1)
    _w1 = filefixer.topLevel1(_top1)
    root.mainloop()

if __name__ == '__main__':
    filefixer.start_up()





